"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("users", [
      // Customers
      {
        F_Name: "Amit",
        L_Name: "Sharma",
        Email: "amit@gmail.com",
        Contact_No: "9123456780",
        Gender: "male",
        Pincode: "100001",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        F_Name: "Nisha",
        L_Name: "Kumar",
        Email: "nisha@gmail.com",
        Contact_No: "9123456781",
        Gender: "female",
        Pincode: "200001",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        F_Name: "Vikas",
        L_Name: "Verma",
        Email: "vikas@gmail.com",
        Contact_No: "9123456782",
        Gender: "male",
        Pincode: "300001",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        F_Name: "Priya",
        L_Name: "Singh",
        Email: "priya@gmail.com",
        Contact_No: "9123456783",
        Gender: "female",
        Pincode: "400001",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        F_Name: "Rohit",
        L_Name: "Patel",
        Email: "rohit@gmail.com",
        Contact_No: "9123456784",
        Gender: "male",
        Pincode: "500001",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        F_Name: "Anjali",
        L_Name: "Gupta",
        Email: "anjali@gmail.com",
        Contact_No: "9123456785",
        Gender: "female",
        Pincode: "600001",
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Employees
      {
        F_Name: "Sanjay",
        L_Name: "Kapoor",
        Email: "sanjay@gmail.com",
        Contact_No: "9123456790",
        Gender: "male",
        Pincode: "100001",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        F_Name: "Sunita",
        L_Name: "Malhotra",
        Email: "sunita@gmail.com",
        Contact_No: "9123456791",
        Gender: "female",
        Pincode: "200001",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        F_Name: "Ravi",
        L_Name: "Rao",
        Email: "ravi@gmail.com",
        Contact_No: "9123456792",
        Gender: "male",
        Pincode: "300001",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        F_Name: "Kiran",
        L_Name: "Bose",
        Email: "kiran@gmail.com",
        Contact_No: "9123456793",
        Gender: "female",
        Pincode: "400001",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        F_Name: "Raj",
        L_Name: "Mehra",
        Email: "raj@gmail.com",
        Contact_No: "9123456794",
        Gender: "male",
        Pincode: "500001",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        F_Name: "Divya",
        L_Name: "Saxena",
        Email: "divya@gmail.com",
        Contact_No: "9123456795",
        Gender: "female",
        Pincode: "600001",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("users", null, {});
  },
};
